### ISSUE TITLE
Did you forget `err`?

### ISSUE THREAD

**Issue by amurchick** [zserge/hid#6]
https://github.com/zserge/hid/blob/master/usb_linux.go#L34
```
func (hid *usbDevice) Open() (err error) {
	if hid.f != nil {
		return errors.New("device is already opened")
	}
	if hid.f, err = os.OpenFile(hid.path, os.O_RDWR, 0644); err != nil {
>		return
	} else {
		return hid.claim()
	}
}
```

Did you forget `err` in marked line?

**Comment by rfjakob** [comment]
No, should be good, because the `err` variable is defined in the function signature:

> func (hid *usbDevice) Open() (err error) {

And set here:

> err = os.OpenFile(hid.path, os.O_RDWR, 0644)

The empty return will use the `err` variable.

**Comment by amurchick** [comment]
Sorry, my mistake.
